name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift version
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.3'

      - name: "Select the latest stable Xcode 13"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "13"
      
      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Code sign certs
        uses: apple-actions/import-codesign-certs@v1
        with: 
        p12-file-base64: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
        p12-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=iOS Simulator,name=iPhone 13
          action: build

      - name: Build for mac catalyst
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=macOS,variant=Mac Catalyst
          action: build  

      - name: Runing tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=iOS Simulator,name=iPhone 13
          action: test

      - name: Runing tests for mac catalyst
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=macOS,variant=Mac Catalyst
          action: test
