name: Swift

on: [push]
  # push:
    # - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift version
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.0'
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'lastest-stable'
      
      - name: Build and tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=iOS Simulator,name=iPhone 13,OS=15.0
          action: build
