name: Swift

on: [push]
  # push:
    # - master

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift version
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.3'

      - name: "Select the latest stable Xcode 13"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "13"
      
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=iOS Simulator,name=iPhone 13
          action: build

      - name: Runing tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=iOS Simulator,name=iPhone 13
          action: test

      - name: Runing tests for mac catalyst
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: githubTest.xcodeproj
          scheme: githubTest
          destination: platform=macOS,variant=Mac Catalyst
          action: test
